version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 99
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '>= 15.x'
      - dependency-name: husky
        versions:
          - '>= 5.x'
